### ISSUE TITLE
Generate the Dominant Colors from a JPEG image [UPDATED]

### ISSUE THREAD

**Issue by loretoparisi** [notmasteryet/jpgjs#40]
I'm trying to use `MMCQ` (Media Mean Cut Quantization) algorithm (from Leptonica library) to get the dominant colors from a jpeg image.
I cannot access `canvas` object and so I'm getting the image via XMLHttpRequest via Jpg.js like the following snippet:

``` javascript
var j = new JpegImage();
j.onload = function() {

                                // Image Data
                                var d = new Object();
                                d.height=350;
                                d.width=350;
                                d.data = new Array();

                                j.copyToImageData(d);

                                var pixels = d.data;
                                var pixelArray = [];
                                var quality = 10;
                                var pixelCount = d.height * d.width * 4;

                                for (var i = 0, offset, r, g, b, a; i < pixelCount; i = i + quality) {
                              offset = i * 4;
                              r = pixels[offset + 0];
                              g = pixels[offset + 1];
                              b = pixels[offset + 2];
                              a = pixels[offset + 3];
                              // If pixel is mostly opaque and not white
                              if (a >= 125) {
                                  if (!(r > 250 && g > 250 && b > 250)) {
                                      pixelArray.push([r, g, b]);
                                  }
                              }
                          }

                                var cmap    = MMCQ.quantize(pixelArray, 8);
                          var palette = cmap.palette();
                                var colors = palette[0];
                                console.log( "JpegImage",$image.parent().parent().attr('id'), colors )

                                styleColors($image, colors);

                            };
                            j.load(imageURL);

```

Since I do not have the canvas imageData object I had to create one like

``` javascript
// Image Data
                                var d = new Object();
                                d.height=350;
                                d.width=350;
                                d.data = new Array();
```

and then copy the resulting ByteArray to the data array:

``` javascript
j.copyToImageData(d);
```

The problem here is that the dominant colors seems to be wrong, and I supposed this could be due the way I shift the jpeg pixels in the bytearray for R,G,B (Alpha channel will be ignored in Jpegs).
My validation dataset is the palette returned by this library https://github.com/lokesh/color-thief that obtain a correct result on PNG images. 
The calculation of the MCQQ 

``` javascript
var cmap    = MMCQ.quantize(pixelArray, 8);
var palette = cmap.palette();
var colors = palette[0];
```

is the same algorithm, that is taken from https://gist.github.com/nrabinowitz/1104622

**Comment by yurydelendik** [comment]
> var pixelCount = d.height \* d.width \* 4;

It shall be `var pixelCount = d.height * d.width;`. Closing as answered

Also it will be more handy if you will publish the complete example online.

**Comment by loretoparisi** [comment]
@yurydelendik Thank you, I will try this and put it online to check the result.

**Comment by loretoparisi** [comment]
@yurydelendik Here is a running example:
http://www.parisilabs.com/colors2/

You can see how it does not match properly the RGB byte array coming out from a `<canvas>` element.

If you look at the logs you can see in action on the same couples of element ids:

``` shell
getColor originofsymmetry [28, 28, 27]
JpegImage originofsymmetry [210, 175, 148]
```

In some cases the result is ok like here with the red colored background image:

![schermata 2015-11-19 alle 02 37 34](https://cloud.githubusercontent.com/assets/163333/11259939/91fe3efa-8e66-11e5-91ea-0b311cad6f2c.jpg)

But in other cases, it fails (where RGB `canvas` ByteArray is correct) like here:
![schermata 2015-11-19 alle 02 37 47](https://cloud.githubusercontent.com/assets/163333/11259951/ad9570de-8e66-11e5-9ab6-18ca090af7e4.jpg)

I have changed to code in order to calculate the size as suggested, but this does not seems to solve the issue.
If this is the case, could you please reopen this issue? 
Thank you.

**Comment by yurydelendik** [comment]
Still not a jpgjs fault: you are calling MMCQ.quantize() with different colorCount parameter values, hence different results.

**Comment by loretoparisi** [comment]
@yurydelendik So you say that the byte array ordering in the Jpeg is correct:

``` javascript
var pixels = d.data;
                                var pixelArray = [];
                                var quality = 10;
                                var pixelCount = d.height * d.width;

                                for (var i = 0, offset, r, g, b, a; i < pixelCount; i = i + quality) {
                              offset = i * 4;
                              r = pixels[offset + 0];
                              g = pixels[offset + 1];
                              b = pixels[offset + 2];
                              a = pixels[offset + 3];
                              // If pixel is mostly opaque and not white
                              if (a >= 125) {
                                  if (!(r > 250 && g > 250 && b > 250)) {
                                      pixelArray.push([r, g, b]);
                                  }
                              }
                          }

                                var cmap    = MMCQ.quantize(pixelArray, 8);
```

but this pixel count 

``` javascript
var pixelCount = d.height * d.width;
```

is wrong? Of course at this point I'm not sure if it is a jpg.js issue, but I don't know about JPEG byte ordering.

**Comment by yurydelendik** [comment]
I'm saying that for getColor() you are calling  MMCQ.quantize(pixelArray, 5), but for JpegImage  MMCQ.quantize(pixelArray, 8);. Is it right?

(BTW, now pixelCount is calculated the same way as in CanvasImage)

**Comment by loretoparisi** [comment]
@yurydelendik Yes!!! At the end the issue was this one!. 

:100: for the support 

Everything works fine on Safari Mobile too

![screen shot 2015-11-19 at 14 03 04](https://cloud.githubusercontent.com/assets/163333/11271488/59ace776-8ec6-11e5-9bee-05467e37d0fe.png)

I want to thank you @larsen for the help about other alternatives to `MMCQ` that I depicted here and helped to find a solution with this: http://stackoverflow.com/questions/33312362/generate-the-dominant-colors-for-an-rgb-image-with-xmlhttprequest/33792749#33792749
